name: Build and Update GitOps

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolher ação:"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: projeto-devops-infra-app
  GITOPS_REPO: lucielly/projeto-devops-gitops
  GITOPS_PATH: apps/devops-app/deployment.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::611635362693:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=v1.${{ github.run_number }}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update image tag in GitOps repo
        run: |
          sed -i "s|image: .*|image: $IMAGE_URI|g" gitops/$GITOPS_PATH

          cd gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add $GITOPS_PATH
          git commit -m "chore: update devops-app image to $IMAGE_URI" || echo "No changes to commit"
          git push