name: Build and Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolher ação:"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - destroy

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: projeto-devops-infra
  ECR_REPOSITORY: projeto-devops-infra-app
  DEPLOYMENT_NAME: devops-app
  NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::611635362693:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: ${{ github.event.inputs.action == 'deploy' }}
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      - name: Deploy to EKS
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" k8s/deployment.yaml

          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE

      - name: Destroy application from EKS
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          kubectl delete -f k8s/service.yaml --ignore-not-found=true
          kubectl delete -f k8s/deployment.yaml --ignore-not-found=true